name: collabsphere

services:
  migrate:
    profiles: [ "migrate" ]
    image: colabsphere-api:${IMAGE_TAG}
    env_file:
      - .env
    volumes:
      - ../platform/internal/platform/db/migrations:/bootstrapapp/migrations:ro
    environment:
      # принимает up, status, down
      MIGRATE_CMD: up
    secrets:
      - dev_password
      - neon_password
    networks:
      - internal.network
    command: ["/migrate"]
    restart: "no"

networks:
  internal.network:
    name: internal.network
    driver: bridge

secrets:
  dev_password:
    file: secrets/postgres/dev/db_password
  neon_password:
    file: secrets/postgres/prod/db_password