services:
  proxy-caddy:
    profiles: ["local", "cloud"]
    image: proxy-caddy:latest
    restart: unless-stopped
    build:
      context: ..//proxy/caddy
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443/tcp"
      - "443:443/udp"
    networks:
      - web.network
      - internal.network
    volumes:
      - ../proxy/caddy/Caddyfile.local:/etc/caddy/Caddyfile.local:ro
      - ../proxy/caddy/Caddyfile.prod:/etc/caddy/Caddyfile.prod:ro
      - ../proxy/caddy/ssl:/etc/caddy/ssl:ro

networks:
  internal.network:
    name: internal.network
    driver: bridge
    external: false
  web.network:
    name: web.network
    external: true